---
jobs:
- name: job-build-bosh-init-cli
  public: true
  serial: true
  plan:
  - aggregate:
    - get: bosh-init
      resource: git-bosh-init
    - get: tutorial
      resource: git-tutorial
  - task: bosh-init-cli-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/static-golang}
      inputs:
        - name: bosh-init
          path: gopath/src/github.com/cloudfoundry/bosh-init
      outputs:
        - name: built-executable
          path: build
      run:
        path: tutorial/60_multi_jobs_bosh_micro_build/task-bosh-init-cli-build.sh
  - put: s3-bosh-init
    params:
      file: build/bosh-init

resources:
- name: git-bosh-init
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-init.git
    branch: master
- name: git-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: fix-lesson-60
- name: s3-bosh-init
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: {{aws-region-name}}
    bucket:  {{aws-bosh-init-bucket}}
    private: false
